#*****************************************************************************************************************
# Copyright (C) Martin Laporte.
#*****************************************************************************************************************

SOURCES := Kernel.cpp

SUBDIRS := Core \
           Intel386 \
           Paging \
           System \
           Threading \
           Utilities

KERNEL := Kernel.bin

-include ../Templates/Global.mak
