#*****************************************************************************************************************
# Copyright (C) Martin Laporte.
#*****************************************************************************************************************

SOURCES := GlobalDescriptorTable.cpp \
           Intel386.cpp \
           Panic.cpp \
           InterruptDescriptorTable.cpp \
           Interrupts.cpp \
           Handlers.cpp \
           PageDirectory.cpp \
           Paging.cpp \
           Tasking.cpp \
           TaskStateSegment.cpp \
           BIOS.cpp \
           BIOSWrapper.S

LIBRARY := Intel386.a

-include ../../Templates/Global.mak
