#*****************************************************************************************************************
# Copyright (C) Martin Laporte.
#*****************************************************************************************************************

SOURCES := Event.cpp \
           Guards.cpp \
           InterruptLock.cpp \
           Mutex.cpp \
           Process.cpp \
           Scheduler.cpp \
           SpinLock.cpp \
           Thread.cpp

LIBRARY = Threading.a

-include ../../Templates/Global.mak
